after :sub_categories, :brands, :status_items, :tormenz do

  Item.create(code:"J10196", name: "Mesa grande" , description: "madera color Chocolate , Ubicación: Sala de Juntas, Color: Chocolate", sub_category_id: SubCategory.where(name: "Mesa de trabajo").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id, in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:1800.00)
  Item.create(code:"J10197", name: "archivero 4 cajones" , description: "5 Archiveros Negros,2 Colo Gris Metalicos y 2 de Madera color Chocolate. , Ubicación: En Sala de Juntas, Color: Negro, ", sub_category_id: SubCategory.where(name: "Archivero").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "office dimension", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:3500.00)
  Item.create(code:"J10198", name: "archivero 4 cajones" , description: "5 Archiveros Negros,2 Colo Gris Metalicos y 2 de Madera color Chocolate. , Ubicación: En Sala de Juntas, Color: Negro, ", sub_category_id: SubCategory.where(name: "Archivero").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "office dimension", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:3500.00)
  Item.create(code:"J10199", name: "archivero 4 cajones" , description: "5 Archiveros Negros,2 Colo Gris Metalicos y 2 de Madera color Chocolate. , Ubicación: En Sala de Juntas, Color: Negro, ", sub_category_id: SubCategory.where(name: "Archivero").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "office dimension", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:3500.00)
  Item.create(code:"J10200", name: "archivero 4 cajones" , description: "5 Archiveros Negros,2 Colo Gris Metalicos y 2 de Madera color Chocolate. , Ubicación: En Sala de Juntas, Color: Negro, ", sub_category_id: SubCategory.where(name: "Archivero").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "office dimension", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:3500.00)
  Item.create(code:"J10201", name: "archivero 4 cajones" , description: "5 Archiveros Negros,2 Colo Gris Metalicos y 2 de Madera color Chocolate. , Ubicación: En Sala de Juntas, Color: Negro, ", sub_category_id: SubCategory.where(name: "Archivero").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "office dimension", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:3500.00)
  Item.create(code:"J10202", name: "archivero 4 cajones" , description: "NA , Ubicación: En Sala de Juntas, Color: Gris", sub_category_id: SubCategory.where(name: "Archivero").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "Tammex", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:3500.00)
  Item.create(code:"J10203", name: "archivero 4 cajones" , description: "NA , Ubicación: En Sala de Juntas, Color: Gris", sub_category_id: SubCategory.where(name: "Archivero").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "Tammex", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:3500.00)
  Item.create(code:"J10204", name: "archivero 4 cajones" , description: "LOS 2 ARCHIVEROS DE MADERA SON DE ESCAIP , Ubicación: Area de Trabajo, Color: Madera",
              sub_category_id: SubCategory.where(name: "Archivero").first.id,
              brand_id: Brand.where(name: "N/A").first.id, model: "de Madera", serial_number: "NA" ,
              status_item_id: StatusItem.where(name: "Malas condiciones").first.id ,
              branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id ,
              in_service_date: Date.strptime("20/2/16", "%d/%m/%y"),
              purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:3500.00)
  Item.create(code:"J10205", name: "archivero 4 cajones" , description: "LOS 2 ARCHIVEROS DE MADERA SON DE ESCAIP , Ubicación: Area de Trabajo, Color: Madera", sub_category_id: SubCategory.where(name: "Archivero").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "de Madera", serial_number: "NA" , status_item_id: StatusItem.where(name: "Malas condiciones").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:3500.00)
  Item.create(code:"J10206", name: "Grabador de camaras" , description: "Color Negro , Ubicación: Sala de Juntas, Color: Negro", sub_category_id: SubCategory.where(name: "N/A").first.id, brand_id: Brand.where(name: "EPCOM").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Nuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:0.00)
  Item.create(code:"J10207", name: "sillas fijas" , description: "Colornegro , Ubicación: Sala de Juntas, Color: Negro", sub_category_id: SubCategory.where(name: "Silla").first.id, brand_id: Brand.where(name: "GENOVA").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:750.00)
  Item.create(code:"J10208", name: "sillas fijas" , description: "Colornegro , Ubicación: Sala de Juntas, Color: Negro", sub_category_id: SubCategory.where(name: "Silla").first.id, brand_id: Brand.where(name: "GENOVA").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:750.00)
  Item.create(code:"J10209", name: "sillas fijas" , description: "Colornegro , Ubicación: Sala de Juntas, Color: Negro", sub_category_id: SubCategory.where(name: "Silla").first.id, brand_id: Brand.where(name: "GENOVA").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:750.00)
  Item.create(code:"J10210", name: "sillas fijas" , description: "Colornegro , Ubicación: Sala de Juntas, Color: Negro", sub_category_id: SubCategory.where(name: "Silla").first.id, brand_id: Brand.where(name: "GENOVA").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:750.00)
  Item.create(code:"J10211", name: "sillas fijas" , description: "Colornegro , Ubicación: Sala de Juntas, Color: Negro", sub_category_id: SubCategory.where(name: "Silla").first.id, brand_id: Brand.where(name: "GENOVA").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:750.00)
  Item.create(code:"J10212", name: "sillas fijas" , description: "Colornegro , Ubicación: Sala de Juntas, Color: Negro", sub_category_id: SubCategory.where(name: "Silla").first.id, brand_id: Brand.where(name: "GENOVA").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:750.00)
  Item.create(code:"J10213", name: "sillas fijas" , description: "Colornegro , Ubicación: en area de trabajo, Color: Negro", sub_category_id: SubCategory.where(name: "Silla").first.id, brand_id: Brand.where(name: "GENOVA").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:750.00)
  Item.create(code:"J10214", name: "sillas fijas" , description: "Colornegro , Ubicación: en area de trabajo, Color: Negro", sub_category_id: SubCategory.where(name: "Silla").first.id, brand_id: Brand.where(name: "GENOVA").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:750.00)
  Item.create(code:"J10215", name: "sillas fijas" , description: "Colornegro , Ubicación: en area de trabajo, Color: Negro", sub_category_id: SubCategory.where(name: "Silla").first.id, brand_id: Brand.where(name: "GENOVA").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:750.00)
  Item.create(code:"J10216", name: "sillas fijas" , description: "Colornegro , Ubicación: en area de trabajo, Color: Negro", sub_category_id: SubCategory.where(name: "Silla").first.id, brand_id: Brand.where(name: "GENOVA").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:750.00)
  Item.create(code:"J10217", name: "sillas fijas" , description: "Colornegro , Ubicación: en area de trabajo, Color: Negro", sub_category_id: SubCategory.where(name: "Silla").first.id, brand_id: Brand.where(name: "GENOVA").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:750.00)
  Item.create(code:"J10218", name: "sillas fijas" , description: "Colornegro , Ubicación: En area de trabajo, Color: Negro", sub_category_id: SubCategory.where(name: "Silla").first.id, brand_id: Brand.where(name: "GENOVA").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:750.00)
  Item.create(code:"J10219", name: "sillas fijas" , description: "Colornegro , Ubicación: en recepcion, Color: Negro", sub_category_id: SubCategory.where(name: "Silla").first.id, brand_id: Brand.where(name: "GENOVA").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:750.00)
  Item.create(code:"J10220", name: "sillas fijas" , description: "Colornegro , Ubicación: en recepcion, Color: Negro", sub_category_id: SubCategory.where(name: "Silla").first.id, brand_id: Brand.where(name: "GENOVA").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:750.00)
  Item.create(code:"J10221", name: "ESCRITORIO EN L" , description: "Madera color Chocolate , Ubicación: en Recepcion, Color: Chocolate", sub_category_id: SubCategory.where(name: "Escritorio").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:2500.00)
  Item.create(code:"J10222", name: "ESCRITORIO EN L" ,
              description: "Madera color Chocolate , Ubicación: En area de trabajo, Color: Chocolate",
              sub_category_id: SubCategory.where(name: "Escritorio").first.id,
              brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" ,
              status_item_id: StatusItem.where(name: "Seminuevo").first.id ,
              branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id ,
                                      in_service_date: Date.strptime("20/2/16", "%d/%m/%y"),
                                      purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:2500.00)
  Item.create(code:"J10223", name: "ESCRITORIO EN L" , description: "Madera color Chocolate , Ubicación: En area de trabajo, Color: Chocolate", sub_category_id: SubCategory.where(name: "Escritorio").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:2500.00)
  Item.create(code:"J10224", name: "ESCRITORIO EN L" , description: "Madera color Chocolate , Ubicación: En area de trabajo, Color: Chocolate", sub_category_id: SubCategory.where(name: "Escritorio").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:2500.00)
  Item.create(code:"J10225", name: "ESCRITORIO EN L" , description: "Madera color Chocolate , Ubicación: En area de trabajo, Color: Chocolate", sub_category_id: SubCategory.where(name: "Escritorio").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:2500.00)
  Item.create(code:"J10226", name: "Frigobar" , description: "Color Negro , Ubicación: Sala de Juntas, Color: Negro", sub_category_id: SubCategory.where(name: "N/A").first.id, brand_id: Brand.where(name: "WIRLPOOL").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Malas condiciones").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:0.00)
  Item.create(code:"J10227", name: "microondas" , description: "Color Negro con Plateado , Ubicación: Sala de Juntas, Color: Negro con Plateado", sub_category_id: SubCategory.where(name: "N/A").first.id, brand_id: Brand.where(name: "LG").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:0.00)
  Item.create(code:"J10228", name: "Rack" , description: "Archivo de 6 divisiones Negro , Ubicación: Sala de Juntas, Color: Negro", sub_category_id: SubCategory.where(name: "N/A").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:1799.00)
  Item.create(code:"J10229", name: "Despachador de Agua" , description: "Despachador de Agua Fria y Caliente color blanco , Ubicación: Area de trabajo, Color: Blanco", sub_category_id: SubCategory.where(name: "N/A").first.id, brand_id: Brand.where(name: "WATERFRESH").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:0.00)
  Item.create(code:"J10230", name: "Mesa de trabajo" , description: "Mesa para trabajo de Gestores color chocolate , Ubicación: Area de trabajo, Color: Chocolate", sub_category_id: SubCategory.where(name: "Mesa de trabajo").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:1800.00)
  Item.create(code:"J10231", name: "Sala" , description: "Color Chocolate de 2 piezas , Ubicación: Recepcion, Color: Chocolate", sub_category_id: SubCategory.where(name: "N/A").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:0.00)
  Item.create(code:"J10232", name: "SILLA EJECUTIVO" , description: "Color negro tipo secretaral , Ubicación: En area de Abogados, Color: Negro", sub_category_id: SubCategory.where(name: "Silla").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Malas condiciones").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:2200.00)
  Item.create(code:"J10233", name: "SILLA EJECUTIVO" , description: "Color negro tipo secretaral , Ubicación: En area de Abogados, Color: Negro", sub_category_id: SubCategory.where(name: "Silla").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Malas condiciones").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:2200.00)
  Item.create(code:"J10234", name: "SILLA EJECUTIVO" , description: "Color negro tipo secretaral , Ubicación: En area de Abogados, Color: Negro", sub_category_id: SubCategory.where(name: "Silla").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Malas condiciones").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:2200.00)
  Item.create(code:"J10235", name: "SILLA EJECUTIVO" , description: "Color negro tipo secretaral , Ubicación: En Recepcion, Color: Negro", sub_category_id: SubCategory.where(name: "Silla").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Malas condiciones").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:2200.00)
  Item.create(code:"J10236", name: "Cuadros decorativos" , description: "Cuadro de quijotes,cuadro café y cuadro con circulos, Ubicación: en Sala de Juntas, Color: Varios", sub_category_id: SubCategory.where(name: "Otros").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:0.00)
  Item.create(code:"J10237", name: "Cuadros decorativos" , description: "Cuadro de quijotes,cuadro café y cuadro con circulos, Ubicación: En Area de Trabajo, Color: Varios", sub_category_id: SubCategory.where(name: "Otros").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:0.00)
  Item.create(code:"J10238", name: "Cuadros decorativos" , description: "Cuadro de quijotes,cuadro café y cuadro con circulos, Ubicación: En Recepcion, Color: Varios", sub_category_id: SubCategory.where(name: "Otros").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:0.00)
  Item.create(code:"J10239", name: "Aire " , description: "Aire acondicionado de techo,blanco y se compro ya usado , Ubicación: Techo, Color: Blanco", sub_category_id: SubCategory.where(name: "Aire acondicionado CELDEK").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Malas condiciones").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("20/2/16", "%d/%m/%y"), purchased_date: Date.strptime("20/2/16", "%d/%m/%y"), price:0.00)
  Item.create(code:"J10240", name: "archivero 3 cajones" , description: "para mejoravit , Ubicación: en modulo del encargado, Color: negro", sub_category_id: SubCategory.where(name: "Archivero").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Nuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("15/2/16", "%d/%m/%y"), purchased_date: Date.strptime("15/2/16", "%d/%m/%y"), price:3500.00)
  Item.create(code:"J10241", name: "archivero 3 cajones" , description: "para mejoravit , Ubicación: En escritorios, Color: negro", sub_category_id: SubCategory.where(name: "Archivero").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Nuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("15/2/16", "%d/%m/%y"), purchased_date: Date.strptime("15/2/16", "%d/%m/%y"), price:2940.00)
  Item.create(code:"J10242", name: "archivero 3 cajones" , description: "para mejoravit , Ubicación: En escritorios, Color: negro", sub_category_id: SubCategory.where(name: "Archivero").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Nuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("15/2/16", "%d/%m/%y"), purchased_date: Date.strptime("15/2/16", "%d/%m/%y"), price:2940.00)
  Item.create(code:"J10243", name: "Grabador de camaras" , description: "equipo de color nego , Ubicación: comedor, Color: negro", sub_category_id: SubCategory.where(name: "N/A").first.id, brand_id: Brand.where(name: "EPCOM").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Nuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("15/2/16", "%d/%m/%y"), purchased_date: Date.strptime("15/2/16", "%d/%m/%y"), price:0.00)
  Item.create(code:"J10244", name: "sillas fijas" , description: "Lugar de 12 persona , Ubicación: en toda la oficina, Color: negras", sub_category_id: SubCategory.where(name: "Silla").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("15/2/16", "%d/%m/%y"), purchased_date: Date.strptime("15/2/16", "%d/%m/%y"), price:750.00)
  Item.create(code:"J10245", name: "sillas fijas" , description: "Lugar de 12 persona , Ubicación: en toda la oficina, Color: negras", sub_category_id: SubCategory.where(name: "Silla").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("15/2/16", "%d/%m/%y"), purchased_date: Date.strptime("15/2/16", "%d/%m/%y"), price:750.00)
  Item.create(code:"J10246", name: "sillas fijas" , description: "Lugar de 12 persona , Ubicación: en toda la oficina, Color: negras", sub_category_id: SubCategory.where(name: "Silla").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("15/2/16", "%d/%m/%y"), purchased_date: Date.strptime("15/2/16", "%d/%m/%y"), price:750.00)
  Item.create(code:"J10247", name: "sillas fijas" , description: "Lugar de 12 persona , Ubicación: en toda la oficina, Color: negras", sub_category_id: SubCategory.where(name: "Silla").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("15/2/16", "%d/%m/%y"), purchased_date: Date.strptime("15/2/16", "%d/%m/%y"), price:750.00)
  Item.create(code:"J10248", name: "ESCRITORIO EN L" , description: "Lugar de 7 persona , Ubicación: en cada modulo, Color: gris", sub_category_id: SubCategory.where(name: "Escritorio").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("15/2/16", "%d/%m/%y"), purchased_date: Date.strptime("15/2/16", "%d/%m/%y"), price:2500.00)
  Item.create(code:"J10249", name: "ESCRITORIO EN L" , description: "Lugar de 7 persona , Ubicación: en cada modulo, Color: gris", sub_category_id: SubCategory.where(name: "Escritorio").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("15/2/16", "%d/%m/%y"), purchased_date: Date.strptime("15/2/16", "%d/%m/%y"), price:2500.00)
  Item.create(code:"J10250", name: "ESCRITORIO EN L" , description: "Lugar de 7 persona , Ubicación: en cada modulo, Color: gris", sub_category_id: SubCategory.where(name: "Escritorio").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("15/2/16", "%d/%m/%y"), purchased_date: Date.strptime("15/2/16", "%d/%m/%y"), price:2500.00)
  Item.create(code:"J10251", name: "ESCRITORIO EN L" , description: "Lugar de 7 persona , Ubicación: en cada modulo, Color: gris", sub_category_id: SubCategory.where(name: "Escritorio").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("15/2/16", "%d/%m/%y"), purchased_date: Date.strptime("15/2/16", "%d/%m/%y"), price:2500.00)
  Item.create(code:"J10252", name: "ESCRITORIO EN L" , description: "Lugar de 7 persona , Ubicación: en cada modulo, Color: gris", sub_category_id: SubCategory.where(name: "Escritorio").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("15/2/16", "%d/%m/%y"), purchased_date: Date.strptime("15/2/16", "%d/%m/%y"), price:2500.00)
  Item.create(code:"J10253", name: "ESCRITORIO EN L" , description: "Lugar de 7 persona , Ubicación: en cada modulo, Color: gris", sub_category_id: SubCategory.where(name: "Escritorio").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("15/2/16", "%d/%m/%y"), purchased_date: Date.strptime("15/2/16", "%d/%m/%y"), price:2500.00)
  Item.create(code:"J10254", name: "ESCRITORIO EN L" , description: "Lugar de 7 persona , Ubicación: en cada modulo, Color: gris", sub_category_id: SubCategory.where(name: "Escritorio").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("15/2/16", "%d/%m/%y"), purchased_date: Date.strptime("15/2/16", "%d/%m/%y"), price:2500.00)
  Item.create(code:"J10255", name: "microondas" , description: "color blanco , Ubicación: en el comedor, Color: blanco", sub_category_id: SubCategory.where(name: "N/A").first.id, brand_id: Brand.where(name: "SHARP").first.id, model: "CAROUSEL", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("15/2/16", "%d/%m/%y"), purchased_date: Date.strptime("15/2/16", "%d/%m/%y"), price:0.00)
  Item.create(code:"J10256", name: "Aire Acondicionado" , description: "NA , Ubicación: en el techo, Color: NA", sub_category_id: SubCategory.where(name: "Aire acondicionado CELDEK").first.id, brand_id: Brand.where(name: "N/A").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Seminuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("15/2/16", "%d/%m/%y"), purchased_date: Date.strptime("15/2/16", "%d/%m/%y"), price:0.00)
  Item.create(code:"J10257", name: "television 37'" , description: "en la sala de espera , Ubicación: en la sala de espera, Color: negro", sub_category_id: SubCategory.where(name: "N/A").first.id, brand_id: Brand.where(name: "SAMSUNG").first.id, model: "NA", serial_number: "NA" , status_item_id: StatusItem.where(name: "Nuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("15/2/16", "%d/%m/%y"), purchased_date: Date.strptime("15/2/16", "%d/%m/%y"), price:0.00)
  Item.create(code:"J10258", name: "Calefacción" , description: "anclada en el modulo principal , Ubicación: en el modulo del encargado, Color: café",
              sub_category_id: SubCategory.where(name: "Calefacción").first.id,
              brand_id: Brand.where(name: "RENZOR").first.id, model: "NA", serial_number: "NA" ,
              status_item_id: StatusItem.where(name: "Seminuevo").first.id ,
              branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id ,
              in_service_date: Date.strptime("15/2/16", "%d/%m/%y"), purchased_date: Date.strptime("15/2/16", "%d/%m/%y"), price:0.00)
  Item.create(code:"BR10567", name: "Bateria de Respaldo" , description: "bateria cuadrada , Ubicación: Acsesorio para asesores , Color: Negro", sub_category_id: SubCategory.where(name: "N/A").first.id, brand_id: Brand.where(name: "ATOMICTHREE").first.id, model: "D2PB60BK", serial_number: "NA" , status_item_id: StatusItem.where(name: "Nuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("28/12/16", "%d/%m/%y"), purchased_date: Date.strptime("28/12/16", "%d/%m/%y"), price:259.00)
  Item.create(code:"BR10568", name: "Bateria de Respaldo" , description: "bateria cuadrada , Ubicación: Acsesorio para asesores , Color: Negro", sub_category_id: SubCategory.where(name: "N/A").first.id, brand_id: Brand.where(name: "ATOMICTHREE").first.id, model: "D2PB60BK", serial_number: "NA" , status_item_id: StatusItem.where(name: "Nuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("28/12/16", "%d/%m/%y"), purchased_date: Date.strptime("28/12/16", "%d/%m/%y"), price:259.00)
  Item.create(code:"BR10569", name: "Bateria de Respaldo" , description: "bateria cuadrada , Ubicación: Acsesorio para asesores , Color: Negro", sub_category_id: SubCategory.where(name: "N/A").first.id, brand_id: Brand.where(name: "ATOMICTHREE").first.id, model: "D2PB60BK", serial_number: "NA" , status_item_id: StatusItem.where(name: "Nuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("28/12/16", "%d/%m/%y"), purchased_date: Date.strptime("28/12/16", "%d/%m/%y"), price:259.00)
  Item.create(code:"BR10570", name: "Bateria de Respaldo" , description: "bateria cuadrada , Ubicación: Acsesorio para asesores , Color: Negro", sub_category_id: SubCategory.where(name: "N/A").first.id, brand_id: Brand.where(name: "ATOMICTHREE").first.id, model: "D2PB60BK", serial_number: "NA" , status_item_id: StatusItem.where(name: "Nuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("28/12/16", "%d/%m/%y"), purchased_date: Date.strptime("28/12/16", "%d/%m/%y"), price:259.00)
  Item.create(code:"BR10571", name: "Bateria de Respaldo" , description: "bateria cuadrada , Ubicación: Acsesorio para asesores , Color: Negro", sub_category_id: SubCategory.where(name: "N/A").first.id, brand_id: Brand.where(name: "ATOMICTHREE").first.id, model: "D2PB60BK", serial_number: "NA" , status_item_id: StatusItem.where(name: "Nuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("28/12/16", "%d/%m/%y"), purchased_date: Date.strptime("28/12/16", "%d/%m/%y"), price:259.00)
  Item.create(code:"BR10572", name: "Bateria de Respaldo" , description: "bateria cuadrada , Ubicación: Acsesorio para asesores , Color: Negro", sub_category_id: SubCategory.where(name: "N/A").first.id, brand_id: Brand.where(name: "ATOMICTHREE").first.id, model: "D2PB60BK", serial_number: "NA" , status_item_id: StatusItem.where(name: "Nuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("28/12/16", "%d/%m/%y"), purchased_date: Date.strptime("28/12/16", "%d/%m/%y"), price:259.00)
  Item.create(code:"BR10573", name: "Bateria de Respaldo" , description: "bateria cuadrada , Ubicación: Acsesorio para asesores , Color: Negro", sub_category_id: SubCategory.where(name: "N/A").first.id, brand_id: Brand.where(name: "ATOMICTHREE").first.id, model: "D2PB60BK", serial_number: "NA" , status_item_id: StatusItem.where(name: "Nuevo").first.id , branch_id: Branch.where(city_id: City.where("name = ? AND state_id = ?", "Juárez",State.where(name: "Chihuahua").first.id ).first.id).first.id , in_service_date: Date.strptime("28/12/16", "%d/%m/%y"), purchased_date: Date.strptime("28/12/16", "%d/%m/%y"), price:259.00)

end
