after :roles do
PermissionRole.create!([
  {role_id: 3, permission_id: 17},
  {role_id: 3, permission_id: 18},
  {role_id: 3, permission_id: 19},
  {role_id: 3, permission_id: 20},
  {role_id: 3, permission_id: 23},
  {role_id: 3, permission_id: 24},
  {role_id: 3, permission_id: 26},
  {role_id: 3, permission_id: 53},
  {role_id: 3, permission_id: 54},
  {role_id: 3, permission_id: 55},
  {role_id: 3, permission_id: 56},
  {role_id: 3, permission_id: 57},
  {role_id: 3, permission_id: 58},
  {role_id: 3, permission_id: 59},
  {role_id: 3, permission_id: 60},
  {role_id: 3, permission_id: 61},
  {role_id: 3, permission_id: 62},
  {role_id: 3, permission_id: 63},
  {role_id: 3, permission_id: 64},
  {role_id: 3, permission_id: 65},
  {role_id: 3, permission_id: 66},
  {role_id: 3, permission_id: 67},
  {role_id: 3, permission_id: 68},
  {role_id: 3, permission_id: 69},
  {role_id: 3, permission_id: 70},
  {role_id: 3, permission_id: 71},
  {role_id: 3, permission_id: 72},
  {role_id: 3, permission_id: 73},
  {role_id: 4, permission_id: 73},
  {role_id: 3, permission_id: 74},
  {role_id: 4, permission_id: 74},
  {role_id: 3, permission_id: 75},
  {role_id: 4, permission_id: 75},
  {role_id: 3, permission_id: 76},
  {role_id: 4, permission_id: 76},
  {role_id: 3, permission_id: 77},
  {role_id: 4, permission_id: 77},
  {role_id: 3, permission_id: 78},
  {role_id: 4, permission_id: 78},
  {role_id: 3, permission_id: 79},
  {role_id: 3, permission_id: 80},
  {role_id: 4, permission_id: 80},
  {role_id: 4, permission_id: 64},
  {role_id: 4, permission_id: 65},
  {role_id: 4, permission_id: 66},
  {role_id: 4, permission_id: 67},
  {role_id: 3, permission_id: 82},
  {role_id: 3, permission_id: 83},
  {role_id: 3, permission_id: 70}
 ])
end

