version: "3"
services:
  app:
    build: .
    environment:
      DATABASE_URL: postgresql://inventory:inventory@db
      PORT: "5000"
    ports:
      - "5000:5000"

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: inventory
      POSTGRES_PASSWORD: inventory
      PGGSSENCMODE: disable
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data


volumes:
  postgresql_data:
  postgresql:
