version: "3"
services:
  app:
    build: .
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: development
    volumes:
      - .:/app
  database:
    image: postgres:12
    environment:
      POSTGRES_USER: inventory
      POSTGRES_PASSWORD: inventory
      PGGSSENCMODE: disable
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgresql_data:
  postgresql: 