development: 
  adapter: postgresql
  encoding: unicode
  database: inventory
  username: inventory
  password: inventory
  host: localhost
test:
  database: inventory
  username: inventory
  password: inventory
  host: localhost
