name: CD

on:
  push:
    branches:  [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          git_remote_url: ${{ secrets.GIT_REMOTE_URL }}
        run: |
          apt update && apt install -yy openssh-client git

          mkdir -p /root/.ssh
          echo "$ssh_private_key" | tr -d '\r' > /root/.ssh/id_rsa
          chmod 600 /root/.ssh/id_rsa
          chmod 700 /root/.ssh

          ssh-keyscan -H -p "22" "104.131.78.234" >> /root/.ssh/known_hosts

          eval "$(ssh-agent -s)"
          ssh-add /root/.ssh/id_rsa

          git remote add dokku dokku@104.131.78.234:inventory
          git push dokku "$commit_sha:refs/heads/master"